
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: always